public with sharing class TeamWorkNewApexClass {
	
	public static void test1(){
		Integer abc=100;
		Integer xyz=200;
		System.debug('abc='+abc);
		System.debug('xyz='+xyz);
        
        System.debug('This is Developer Console Statement..........');
		
		String XY='Jansi';
		
         System.debug('Thank You.drfjvdjhgvjfgbhrf');
        System.debug('Thank You............................');
	}
	
    
}